import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  en: {
    // App
    appName: 'EVA POS',
    
    // Navigation
    dashboard: 'Dashboard',
    pointOfSale: 'Point of Sale',
    inventory: 'Inventory',
    purchasing: 'Purchasing',
    customers: 'Customers',
    returns: 'Returns',
    expenses: 'Expenses',
    reports: 'Reports',
    settings: 'Settings',
    users: 'Users',
    branches: 'Branches',
    backup: 'Backup',
    logout: 'Logout',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    print: 'Print',
    close: 'Close',
    refresh: 'Refresh',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    
    // Dashboard
    welcomeBack: 'Welcome back',
    todaySales: 'Today\'s Sales',
    totalRevenue: 'Total Revenue',
    totalProfit: 'Total Profit',
    lowStock: 'Low Stock Items',
    avgTicket: 'Avg Ticket',
    netProfit: 'Net Profit',
    transactions: 'transactions',
    perSale: 'Per sale',
    margin: 'margin',
    afterExpenses: 'After expenses',
    needAttention: 'Need attention',
    allGood: 'All good',
    todaysTotal: 'Today\'s total',
    recentSales: 'Recent Sales',
    lowStockAlert: 'Low Stock Alert',
    viewAll: 'View All',
    noSalesToday: 'No sales today',
    startSelling: 'Start Selling',
    allItemsInStock: 'All items in stock',
    quickActions: 'Quick Actions',
    newSale: 'New Sale',
    viewReports: 'View Reports',
    backupData: 'Backup Data',
    left: 'left',
    
    // Products
    products: 'Products',
    productName: 'Product Name',
    category: 'Category',
    price: 'Price',
    stock: 'Stock',
    barcode: 'Barcode',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    
    // Sales
    sale: 'Sale',
    sales: 'Sales',
    totalAmount: 'Total Amount',
    discount: 'Discount',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    completeSale: 'Complete Sale',
    
    // Settings
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    appearance: 'Appearance',
    systemSettings: 'System Settings',
    theme: 'Theme',
    selectTheme: 'Choose your preferred color theme',
    darkMode: 'Dark Mode',
    darkModeDesc: 'Easy on the eyes',
    lightMode: 'Light Mode',
    lightModeDesc: 'Soft and comfortable',
    
    // Printing
    printReceipt: 'Print Receipt',
    printLabel: 'Print Label',
    printReport: 'Print Report',
    printer: 'Printer',
    
    // Auth
    login: 'Login',
    username: 'Username',
    password: 'Password',
    
    // Backup
    createBackup: 'Create Backup',
    restoreBackup: 'Restore Backup',
    selectBackupFile: 'Select Backup File',
    
    // POS Page
    scanBarcode: 'Scan barcode...',
    scanReceiptBarcode: 'Scan the barcode from the receipt to automatically load sale information',
    returnToStock: 'Return to stock',
    exchangeReturningItem: 'Exchange - returning item',
    exchangeNewItem: 'Exchange - new item',
    scan: 'Scan',
    cart: 'Cart',
    item: 'item',
    items: 'items',
    clear: 'Clear',
    clearCart: 'Clear cart',
    clearAllItems: 'Clear all items from cart?',
    returns: 'Returns',
    processReturns: 'Process returns',
    posTabs: 'POS Tabs',
    holdUpToCustomers: 'Hold up to {count} customers',
    emptyTab: 'Empty tab',
    empty: 'Empty',
    noItemsInCart: 'No items in cart.',
    itemHeader: 'Item',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    lineTotal: 'Line Total',
    removeItem: 'Remove item',
    customer: 'Customer',
    walkIn: 'Walk-in',
    discount: 'Discount',
    discountByAmount: 'Discount by fixed amount',
    discountByPercent: 'Discount by percentage',
    discountByFinalPrice: 'Enter final price customer will pay',
    finalPrice: 'Final Price',
    enterFinalPrice: 'Enter final price',
    amount: 'Amount',
    percent: 'Percent',
    clearDiscount: 'Clear discount',
    paymentMethod: 'Payment Method',
    card: 'Card',
    mixed: 'Mixed',
    subtotal: 'Subtotal',
    total: 'Total',
    estimatedProfit: 'Estimated Profit',
    completeSale: 'Complete Sale',
    processing: 'Processing…',
    addItemsFirst: 'Add items to cart first',
    completeSaleEnter: 'Complete sale (Enter)',
    outOfStock: 'is out of stock. Cannot add to cart.',
    onlyXAvailable: 'Only {count} {item} available in stock for "{name}".',
    outOfStockCannotAdd: 'is out of stock. Cannot add more.',
    addAtLeastOne: 'Add at least one product to the cart.',
    cannotCompleteOutOfStock: 'Cannot complete sale: The following items are out of stock: {items}. Please remove them from the cart.',
    cannotCompleteQuantity: 'Cannot complete sale: Quantity exceeds available stock for: {details}. Please adjust quantities.',
    failedToCompleteSale: 'Failed to complete sale.',
    pleaseEnterBarcode: 'Please enter a barcode or SKU (at least 5 characters)',
    inCart: 'in cart',
    
    // Settings
    configureSystem: 'Configure your system settings',
    exchangeRate: 'Exchange Rate (USD → IQD)',
    setExchangeRate: 'Set the current exchange rate for currency conversion',
    currentRate: 'Current Rate',
    per1USD: 'per 1 USD',
    updateExchangeRate: 'Update Exchange Rate',
    enterNewRate: 'Enter new rate',
    update: 'Update',
    updating: 'Updating...',
    exchangeRateUpdated: 'Exchange rate updated successfully!',
    profitMarginCalculator: 'Profit Margin Calculator',
    calculateProfitMargins: 'Calculate profit margins based on cost and selling price',
    costUSD: 'Cost (USD)',
    salePriceIQD: 'Sale Price (IQD)',
    profitMargin: 'Profit Margin',
    profitAmount: 'Profit Amount',
    exchangeRateUsed: 'Exchange Rate Used',
    formula: 'Formula',
    marginFormula: 'Margin = ((Sale Price - Cost × Rate) / (Cost × Rate)) × 100',
    moreSettingsComing: 'More settings coming soon...',
    labelSettings: 'Label Settings',
    customizeBarcodeLabels: 'Customize how barcode labels are printed',
    basicSettings: 'Basic Settings',
    labelSize: 'Label Size',
    smallLabel: '2" × 1" (Small)',
    largeLabel: '4" × 2" (Large)',
    fontSize: 'Font Size (px)',
    textAlignment: 'Text Alignment',
    left: 'Left',
    center: 'Center',
    right: 'Right',
    labelPadding: 'Label Padding (px)',
    showHideElements: 'Show/Hide Elements',
    productName: 'Product Name',
    variantColorSize: 'Variant (Color/Size)',
    sku: 'SKU',
    price: 'Price',
    barcodeSettings: 'Barcode Settings',
    barcodeHeight: 'Barcode Height',
    barcodeWidth: 'Barcode Width',
    customTextFields: 'Custom Text Fields',
    addCustomText: 'Add custom text that appears on all labels (e.g., "VIP", "BIG SIZE", etc.)',
    customText1: 'Custom Text 1',
    customText2: 'Custom Text 2',
    customText2Auto: 'Automatically set to product name',
    customText3: 'Custom Text 3',
    storeName: 'Store Name',
    saveLabelSettings: 'Save Label Settings',
    saving: 'Saving...',
    labelSettingsSaved: 'Label settings saved successfully!',
    
    // Barcode Label Modal
    printBarcodeLabel: 'Print Barcode Label',
    quantity: 'Quantity',
    printer: 'Printer',
    systemDefault: 'System Default',
    preview: 'Preview',
    size: 'Size',
    customizeInSettings: 'Customize label settings in Settings page',
    loadingLabelSettings: 'Loading label settings...',
    thisProductNoBarcode: 'This product does not have a barcode assigned. Please add a barcode first.',
    barcodeNotReady: 'Barcode is not ready. Please wait a moment and try again.',
    
    // Common errors and messages
    pleaseEnterValidRate: 'Please enter a valid rate',
    failedToUpdateRate: 'Failed to update rate',
    
    // Products Page
    manageCatalog: 'Manage catalog, pricing, and variants.',
    importExcel: 'Import Excel',
    addProduct: 'Add Product',
    loadingProducts: 'Loading products…',
    adjustStock: 'Adjust Stock',
    actions: 'ACTIONS',
    stock: 'STOCK',
    avgCostUSD: 'AVG COST (USD)',
    priceIQD: 'PRICE (IQD)',
    size: 'SIZE',
    color: 'COLOR',
    barcode: 'BARCODE',
    sku: 'SKU',
    name: 'NAME',
    areYouSureDelete: 'Are you sure you want to delete "{name}" ({sku})? This action cannot be undone.',
    
    // Suppliers Page
    newSupplier: 'New Supplier',
    createSupplier: 'Create Supplier',
    supplierName: 'Name',
    contactName: 'Contact Name',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    notes: 'Notes',
    saveSupplier: 'Save Supplier',
    saving: 'Saving…',
    loadingSuppliers: 'Loading suppliers…',
    noSuppliersYet: 'No suppliers yet. Add your first vendor.',
    supplierNameRequired: 'Supplier name is required.',
    failedToCreateSupplier: 'Failed to create supplier.',
    failedToLoadSuppliers: 'Failed to load suppliers.',
    active: 'Active',
    inactive: 'Inactive',
    
    // Purchase Orders Page
    purchaseOrders: 'Purchase Orders',
    trackInboundStock: 'Track inbound stock and supplier invoices.',
    createPO: 'Create PO',
    addItems: 'Add Items',
    selectSupplier: 'Select supplier',
    reference: 'Reference',
    draftItems: 'Draft Items',
    noItemsInDraft: 'No items in the draft. Add variants to build a PO',
    subtotalUSD: 'Subtotal USD',
    subtotalIQD: 'Subtotal IQD',
    recentPurchaseOrders: 'Recent Purchase Orders',
    loadingPurchaseOrders: 'Loading purchase orders…',
    noPurchaseOrdersRecorded: 'No purchase orders recorded.',
    selectSupplierAndAddItems: 'Select a supplier and add at least one item.',
    failedToLoadPurchaseOrders: 'Failed to load purchase orders.',
    failedToCreatePO: 'Failed to create PO.',
    
    // Customers Page
    customersLoyalty: 'Customers & Loyalty',
    trackLoyalty: 'Track loyalty, visits, and purchase history.',
    newCustomer: 'New Customer',
    searchCustomers: 'Search customers...',
    addCustomer: 'Add Customer',
    saveCustomer: 'Save Customer',
    loadingCustomers: 'Loading customers…',
    noCustomersMatch: 'No customers match your search.',
    noPhone: 'No phone',
    visits: 'Visits',
    spent: 'Spent',
    totalSpent: 'Total Spent',
    selectCustomerToView: 'Select a customer to view details.',
    noPhoneOnFile: 'No phone on file',
    noRecordedPurchases: 'No recorded purchases.',
    customerNameRequired: 'Customer name is required.',
    failedToLoadCustomers: 'Failed to load customers.',
    failedToCreateCustomer: 'Failed to create customer.',
    
    // Returns Page
    returnsExchanges: 'Returns & Exchanges',
    processRefunds: 'Process refunds, returns, and exchanges quickly.',
    completeReturn: 'Complete Return',
    addItem: 'Add Item',
    refundTotal: 'Refund Total',
    type: 'Type',
    saleIDOptional: 'Sale ID (optional)',
    enterSaleID: 'Enter sale ID',
    lookup: 'lookup',
    reason: 'Reason',
    reasonOrNotes: 'Reason or notes',
    returnItems: 'Return Items',
    noItemsAddedYet: 'No items added yet.',
    recentReturns: 'Recent Returns',
    loadingReturns: 'Loading returns…',
    noReturnsRecorded: 'No returns recorded.',
    processing: 'Processing…',
    failedToLoadReturns: 'Failed to load returns.',
    failedToCompleteReturn: 'Failed to complete return.',
    returnWithReceipt: 'Return with receipt',
    returnWithoutReceipt: 'Return without receipt',
    exchange: 'Exchange',
    
    // Expenses Page
    expenses: 'Expenses',
    trackOperatingCosts: 'Track operating costs and profitability.',
    exportToCSV: 'Export to CSV',
    total: 'Total',
    startDate: 'Start Date',
    endDate: 'End Date',
    category: 'Category',
    all: 'All',
    addExpense: 'Add Expense',
    amountIQD: 'Amount (IQD)',
    date: 'Date',
    saveExpense: 'Save Expense',
    selectOrTypeCategory: 'Select or type a category',
    loadingExpenses: 'Loading expenses…',
    noExpensesInRange: 'No expenses in this range.',
    failedToLoadExpenses: 'Failed to load expenses.',
    failedToSaveExpense: 'Failed to save expense.',
    
    // Reports Page
    advancedReports: 'Advanced Reports',
    endToEndInsight: 'End-to-end insight into your clothing store performance.',
    print: 'Print',
    exportToExcel: 'Export to Excel',
    runReport: 'Run Report',
    loading: 'Loading…',
    revenueIQD: 'Revenue (IQD)',
    costOfGoods: 'Cost of Goods',
    netProfit: 'Net Profit',
    inventoryValue: 'Inventory Value',
    failedToPrintReport: 'Failed to print report',
    viewDetails: 'View Details',
    noProductsFound: 'No products found. Add your first item.',
    uncategorized: 'Uncategorized',
    noBarcode: 'No barcode',
    manageVendorRelationships: 'Manage vendor relationships and contact details.',
    status: 'Status',
  },
  
  ar: {
    // App
    appName: 'إيفا نقاط البيع',
    
    // Navigation
    dashboard: 'لوحة التحكم',
    pointOfSale: 'نقطة البيع',
    inventory: 'المخزون',
    purchasing: 'المشتريات',
    customers: 'العملاء',
    returns: 'المرتجعات',
    expenses: 'المصروفات',
    reports: 'التقارير',
    settings: 'الإعدادات',
    users: 'المستخدمين',
    branches: 'الفروع',
    backup: 'النسخ الاحتياطي',
    logout: 'تسجيل الخروج',
    
    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    print: 'طباعة',
    close: 'إغلاق',
    refresh: 'تحديث',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    error: 'خطأ',
    success: 'نجح',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    
    // Dashboard
    welcomeBack: 'مرحباً بعودتك',
    todaySales: 'مبيعات اليوم',
    totalRevenue: 'إجمالي الإيرادات',
    totalProfit: 'إجمالي الربح',
    lowStock: 'منتجات منخفضة المخزون',
    avgTicket: 'متوسط الفاتورة',
    netProfit: 'صافي الربح',
    transactions: 'معاملات',
    perSale: 'لكل عملية بيع',
    margin: 'هامش',
    afterExpenses: 'بعد المصروفات',
    needAttention: 'تحتاج انتباه',
    allGood: 'كل شيء جيد',
    todaysTotal: 'إجمالي اليوم',
    recentSales: 'المبيعات الأخيرة',
    lowStockAlert: 'تنبيه المخزون المنخفض',
    viewAll: 'عرض الكل',
    noSalesToday: 'لا توجد مبيعات اليوم',
    startSelling: 'ابدأ البيع',
    allItemsInStock: 'جميع المنتجات متوفرة',
    quickActions: 'إجراءات سريعة',
    newSale: 'عملية بيع جديدة',
    viewReports: 'عرض التقارير',
    backupData: 'نسخ احتياطي للبيانات',
    left: 'متبقي',
    
    // Products
    products: 'المنتجات',
    productName: 'اسم المنتج',
    category: 'الفئة',
    price: 'السعر',
    stock: 'المخزون',
    barcode: 'الباركود',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل منتج',
    
    // Sales
    sale: 'بيع',
    sales: 'المبيعات',
    totalAmount: 'المبلغ الإجمالي',
    discount: 'الخصم',
    paymentMethod: 'طريقة الدفع',
    cash: 'نقدي',
    card: 'بطاقة',
    completeSale: 'إتمام البيع',
    
    // Settings
    language: 'اللغة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    appearance: 'المظهر',
    systemSettings: 'إعدادات النظام',
    theme: 'المظهر',
    selectTheme: 'اختر مظهر الألوان المفضل لديك',
    darkMode: 'الوضع الداكن',
    darkModeDesc: 'مريح للعين',
    lightMode: 'الوضع الفاتح',
    lightModeDesc: 'ناعم ومريح',
    
    // Printing
    printReceipt: 'طباعة إيصال',
    printLabel: 'طباعة ملصق',
    printReport: 'طباعة تقرير',
    printer: 'الطابعة',
    
    // Auth
    login: 'تسجيل الدخول',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    
    // Backup
    createBackup: 'إنشاء نسخة احتياطية',
    restoreBackup: 'استعادة نسخة احتياطية',
    selectBackupFile: 'اختيار ملف النسخة',
    
    // POS Page
    scanBarcode: 'امسح الباركود...',
    scanReceiptBarcode: 'امسح الباركود من الإيصال لتحميل معلومات البيع تلقائياً',
    returnToStock: 'إرجاع إلى المخزون',
    exchangeReturningItem: 'تبديل - إرجاع عنصر',
    exchangeNewItem: 'تبديل - عنصر جديد',
    scan: 'امسح',
    cart: 'السلة',
    item: 'عنصر',
    items: 'عناصر',
    clear: 'مسح',
    clearCart: 'مسح السلة',
    clearAllItems: 'مسح جميع العناصر من السلة؟',
    returns: 'المرتجعات',
    processReturns: 'معالجة المرتجعات',
    posTabs: 'تبويبات نقطة البيع',
    holdUpToCustomers: 'يمكن الاحتفاظ بما يصل إلى {count} عملاء',
    emptyTab: 'تبويب فارغ',
    empty: 'فارغ',
    noItemsInCart: 'لا توجد عناصر في السلة.',
    itemHeader: 'العنصر',
    qty: 'الكمية',
    unitPrice: 'سعر الوحدة',
    lineTotal: 'الإجمالي',
    removeItem: 'إزالة العنصر',
    customer: 'العميل',
    walkIn: 'مشاة',
    discount: 'الخصم',
    discountByAmount: 'خصم بمبلغ ثابت',
    discountByPercent: 'خصم بنسبة مئوية',
    discountByFinalPrice: 'أدخل السعر النهائي الذي سيدفعه العميل',
    finalPrice: 'السعر النهائي',
    enterFinalPrice: 'أدخل السعر النهائي',
    amount: 'المبلغ',
    percent: 'النسبة',
    clearDiscount: 'مسح الخصم',
    paymentMethod: 'طريقة الدفع',
    card: 'بطاقة',
    mixed: 'مختلط',
    subtotal: 'المجموع الفرعي',
    total: 'الإجمالي',
    estimatedProfit: 'الربح المقدر',
    completeSale: 'إتمام البيع',
    processing: 'جاري المعالجة…',
    addItemsFirst: 'أضف عناصر إلى السلة أولاً',
    completeSaleEnter: 'إتمام البيع (Enter)',
    outOfStock: 'نفد من المخزون. لا يمكن إضافته إلى السلة.',
    onlyXAvailable: 'متوفر فقط {count} {item} في المخزون لـ "{name}".',
    outOfStockCannotAdd: 'نفد من المخزون. لا يمكن إضافة المزيد.',
    addAtLeastOne: 'أضف منتجاً واحداً على الأقل إلى السلة.',
    cannotCompleteOutOfStock: 'لا يمكن إتمام البيع: العناصر التالية نفدت من المخزون: {items}. يرجى إزالتها من السلة.',
    cannotCompleteQuantity: 'لا يمكن إتمام البيع: الكمية تتجاوز المخزون المتاح لـ: {details}. يرجى تعديل الكميات.',
    failedToCompleteSale: 'فشل إتمام البيع.',
    pleaseEnterBarcode: 'يرجى إدخال باركود أو رمز SKU (5 أحرف على الأقل)',
    inCart: 'في السلة',
    
    // Settings
    configureSystem: 'تكوين إعدادات النظام',
    exchangeRate: 'سعر الصرف (USD → IQD)',
    setExchangeRate: 'تعيين سعر الصرف الحالي لتحويل العملة',
    currentRate: 'السعر الحالي',
    per1USD: 'لكل 1 دولار',
    updateExchangeRate: 'تحديث سعر الصرف',
    enterNewRate: 'أدخل سعر جديد',
    update: 'تحديث',
    updating: 'جاري التحديث...',
    exchangeRateUpdated: 'تم تحديث سعر الصرف بنجاح!',
    profitMarginCalculator: 'حاسبة هامش الربح',
    calculateProfitMargins: 'احسب هوامش الربح بناءً على التكلفة وسعر البيع',
    costUSD: 'التكلفة (USD)',
    salePriceIQD: 'سعر البيع (IQD)',
    profitMargin: 'هامش الربح',
    profitAmount: 'مبلغ الربح',
    exchangeRateUsed: 'سعر الصرف المستخدم',
    formula: 'الصيغة',
    marginFormula: 'الهامش = ((سعر البيع - التكلفة × السعر) / (التكلفة × السعر)) × 100',
    moreSettingsComing: 'المزيد من الإعدادات قريباً...',
    labelSettings: 'إعدادات الملصقات',
    customizeBarcodeLabels: 'تخصيص كيفية طباعة ملصقات الباركود',
    basicSettings: 'الإعدادات الأساسية',
    labelSize: 'حجم الملصق',
    smallLabel: '2" × 1" (صغير)',
    largeLabel: '4" × 2" (كبير)',
    fontSize: 'حجم الخط (بكسل)',
    textAlignment: 'محاذاة النص',
    left: 'يسار',
    center: 'وسط',
    right: 'يمين',
    labelPadding: 'الحشو (بكسل)',
    showHideElements: 'إظهار/إخفاء العناصر',
    productName: 'اسم المنتج',
    variantColorSize: 'المتغير (اللون/المقاس)',
    sku: 'رمز SKU',
    price: 'السعر',
    barcodeSettings: 'إعدادات الباركود',
    barcodeHeight: 'ارتفاع الباركود',
    barcodeWidth: 'عرض الباركود',
    customTextFields: 'حقول النص المخصصة',
    addCustomText: 'أضف نصاً مخصصاً يظهر على جميع الملصقات (مثل "VIP"، "BIG SIZE"، إلخ)',
    customText1: 'النص المخصص 1',
    customText2: 'النص المخصص 2',
    customText2Auto: 'يتم تعيينه تلقائياً إلى اسم المنتج',
    customText3: 'النص المخصص 3',
    storeName: 'اسم المتجر',
    saveLabelSettings: 'حفظ إعدادات الملصقات',
    saving: 'جاري الحفظ...',
    labelSettingsSaved: 'تم حفظ إعدادات الملصقات بنجاح!',
    
    // Barcode Label Modal
    printBarcodeLabel: 'طباعة ملصق الباركود',
    quantity: 'الكمية',
    printer: 'الطابعة',
    systemDefault: 'الافتراضي للنظام',
    preview: 'معاينة',
    size: 'الحجم',
    customizeInSettings: 'تخصيص إعدادات الملصقات في صفحة الإعدادات',
    loadingLabelSettings: 'جاري تحميل إعدادات الملصقات...',
    thisProductNoBarcode: 'هذا المنتج لا يحتوي على باركود. يرجى إضافة باركود أولاً.',
    barcodeNotReady: 'الباركود غير جاهز. يرجى الانتظار قليلاً والمحاولة مرة أخرى.',
    
    // Common errors and messages
    pleaseEnterValidRate: 'يرجى إدخال سعر صحيح',
    failedToUpdateRate: 'فشل تحديث السعر',
    
    // Products Page
    manageCatalog: 'إدارة الكتالوج والأسعار والمتغيرات.',
    importExcel: 'استيراد Excel',
    addProduct: 'إضافة منتج',
    loadingProducts: 'جاري تحميل المنتجات…',
    adjustStock: 'تعديل المخزون',
    actions: 'الإجراءات',
    stock: 'المخزون',
    avgCostUSD: 'متوسط التكلفة (USD)',
    priceIQD: 'السعر (IQD)',
    size: 'المقاس',
    color: 'اللون',
    barcode: 'الباركود',
    sku: 'رمز SKU',
    name: 'الاسم',
    areYouSureDelete: 'هل أنت متأكد أنك تريد حذف "{name}" ({sku})؟ لا يمكن التراجع عن هذا الإجراء.',
    
    // Suppliers Page
    newSupplier: 'مورد جديد',
    createSupplier: 'إنشاء مورد',
    supplierName: 'الاسم',
    contactName: 'اسم جهة الاتصال',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    notes: 'ملاحظات',
    saveSupplier: 'حفظ المورد',
    saving: 'جاري الحفظ…',
    loadingSuppliers: 'جاري تحميل الموردين…',
    noSuppliersYet: 'لا يوجد موردون بعد. أضف أول مورد.',
    supplierNameRequired: 'اسم المورد مطلوب.',
    failedToCreateSupplier: 'فشل إنشاء المورد.',
    failedToLoadSuppliers: 'فشل تحميل الموردين.',
    active: 'نشط',
    inactive: 'غير نشط',
    
    // Purchase Orders Page
    purchaseOrders: 'أوامر الشراء',
    trackInboundStock: 'تتبع المخزون الوارد وفواتير الموردين.',
    createPO: 'إنشاء أمر شراء',
    addItems: 'إضافة عناصر',
    selectSupplier: 'اختر مورد',
    reference: 'المرجع',
    draftItems: 'العناصر المسودة',
    noItemsInDraft: 'لا توجد عناصر في المسودة. أضف متغيرات لإنشاء أمر شراء',
    subtotalUSD: 'المجموع الفرعي USD',
    subtotalIQD: 'المجموع الفرعي IQD',
    recentPurchaseOrders: 'أوامر الشراء الأخيرة',
    loadingPurchaseOrders: 'جاري تحميل أوامر الشراء…',
    noPurchaseOrdersRecorded: 'لا توجد أوامر شراء مسجلة.',
    selectSupplierAndAddItems: 'اختر مورداً وأضف عنصراً واحداً على الأقل.',
    failedToLoadPurchaseOrders: 'فشل تحميل أوامر الشراء.',
    failedToCreatePO: 'فشل إنشاء أمر الشراء.',
    
    // Customers Page
    customersLoyalty: 'العملاء والولاء',
    trackLoyalty: 'تتبع الولاء والزيارات وسجل المشتريات.',
    newCustomer: 'عميل جديد',
    searchCustomers: 'بحث عن العملاء...',
    addCustomer: 'إضافة عميل',
    saveCustomer: 'حفظ العميل',
    loadingCustomers: 'جاري تحميل العملاء…',
    noCustomersMatch: 'لا يوجد عملاء يطابقون بحثك.',
    noPhone: 'لا يوجد هاتف',
    visits: 'الزيارات',
    spent: 'المصروف',
    totalSpent: 'إجمالي المصروف',
    selectCustomerToView: 'اختر عميلاً لعرض التفاصيل.',
    noPhoneOnFile: 'لا يوجد هاتف في الملف',
    noRecordedPurchases: 'لا توجد مشتريات مسجلة.',
    customerNameRequired: 'اسم العميل مطلوب.',
    failedToLoadCustomers: 'فشل تحميل العملاء.',
    failedToCreateCustomer: 'فشل إنشاء العميل.',
    
    // Returns Page
    returnsExchanges: 'المرتجعات والتبديلات',
    processRefunds: 'معالجة الاسترداد والمرتجعات والتبديلات بسرعة.',
    completeReturn: 'إتمام الإرجاع',
    addItem: 'إضافة عنصر',
    refundTotal: 'إجمالي الاسترداد',
    type: 'النوع',
    saleIDOptional: 'رقم البيع (اختياري)',
    enterSaleID: 'أدخل رقم البيع',
    lookup: 'بحث',
    reason: 'السبب',
    reasonOrNotes: 'السبب أو الملاحظات',
    returnItems: 'عناصر الإرجاع',
    noItemsAddedYet: 'لم تتم إضافة عناصر بعد.',
    recentReturns: 'المرتجعات الأخيرة',
    loadingReturns: 'جاري تحميل المرتجعات…',
    noReturnsRecorded: 'لا توجد مرتجعات مسجلة.',
    processing: 'جاري المعالجة…',
    failedToLoadReturns: 'فشل تحميل المرتجعات.',
    failedToCompleteReturn: 'فشل إتمام الإرجاع.',
    returnWithReceipt: 'إرجاع مع إيصال',
    returnWithoutReceipt: 'إرجاع بدون إيصال',
    exchange: 'تبديل',
    
    // Expenses Page
    expenses: 'المصروفات',
    trackOperatingCosts: 'تتبع تكاليف التشغيل والربحية.',
    exportToCSV: 'تصدير إلى CSV',
    total: 'الإجمالي',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    category: 'الفئة',
    all: 'الكل',
    addExpense: 'إضافة مصروف',
    amountIQD: 'المبلغ (IQD)',
    date: 'التاريخ',
    saveExpense: 'حفظ المصروف',
    selectOrTypeCategory: 'اختر أو اكتب فئة',
    loadingExpenses: 'جاري تحميل المصروفات…',
    noExpensesInRange: 'لا توجد مصروفات في هذا النطاق.',
    failedToLoadExpenses: 'فشل تحميل المصروفات.',
    failedToSaveExpense: 'فشل حفظ المصروف.',
    
    // Reports Page
    advancedReports: 'التقارير المتقدمة',
    endToEndInsight: 'رؤية شاملة لأداء متجر الملابس الخاص بك.',
    print: 'طباعة',
    exportToExcel: 'تصدير إلى Excel',
    runReport: 'تشغيل التقرير',
    loading: 'جاري التحميل…',
    revenueIQD: 'الإيرادات (IQD)',
    costOfGoods: 'تكلفة البضائع',
    netProfit: 'صافي الربح',
    inventoryValue: 'قيمة المخزون',
    failedToPrintReport: 'فشل طباعة التقرير',
    viewDetails: 'عرض التفاصيل',
    noProductsFound: 'لم يتم العثور على منتجات. أضف أول عنصر.',
    uncategorized: 'غير مصنف',
    noBarcode: 'لا يوجد باركود',
    manageVendorRelationships: 'إدارة علاقات الموردين وتفاصيل الاتصال.',
    status: 'الحالة',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('appLanguage') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguageState(savedLanguage);
      applyLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
    applyLanguage(lang);
  };

  const applyLanguage = (lang: Language) => {
    // Set HTML dir attribute for RTL
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations['en']] || key;
    if (params) {
      Object.keys(params).forEach((paramKey) => {
        translation = translation.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }
    return translation;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

