import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  en: {
    // App
    appName: 'EVA POS',

    // Navigation
    dashboard: 'Dashboard',
    pointOfSale: 'Point of Sale',
    inventory: 'Inventory',
    purchasing: 'Purchasing',
    customers: 'Customers',
    returns: 'Returns',
    expenses: 'Expenses',
    reports: 'Reports',
    settings: 'Settings',
    users: 'Users',
    branches: 'Branches',
    backup: 'Backup',
    logout: 'Logout',
    suppliers: 'Suppliers',
    offlineMode: 'Offline',
    lockPOS: 'Lock POS',
    unlockPOS: 'Unlock POS',
    locked: 'Locked',
    unlocked: 'Unlocked',

    // Date Presets
    today: 'Today',
    yesterday: 'Yesterday',
    last2days: 'Last 2 Days',
    last7days: 'Last 7 Days',
    last30days: 'Last 30 Days',
    last90days: 'Last 90 Days',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    customRange: 'Custom Range',
    to: 'to',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    print: 'Print',
    close: 'Close',
    refresh: 'Refresh',
    loading: 'Loading...',
    noData: 'No data available',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',

    // Dashboard
    welcomeBack: 'Welcome back',
    todaySales: 'Today\'s Sales',
    totalRevenue: 'Total Revenue',
    totalProfit: 'Total Profit',
    lowStock: 'Low Stock Items',
    avgTicket: 'Avg Ticket',
    netProfit: 'Net Profit',
    transactions: 'transactions',
    perSale: 'Per sale',
    margin: 'margin',
    afterExpenses: 'After expenses',
    needAttention: 'Need attention',
    allGood: 'All good',
    todaysTotal: 'Today\'s total',
    recentSales: 'Recent Sales',
    lowStockAlert: 'Low Stock Alert',
    viewAll: 'View All',
    noSalesToday: 'No sales today',
    startSelling: 'Start Selling',
    allItemsInStock: 'All items in stock',
    quickActions: 'Quick Actions',
    newSale: 'New Sale',
    editProduct: 'Edit Product',
    productName: 'Product Name',
    sellingPriceIQD: 'Selling Price (IQD)',
    saving: 'Saving...',
    failedToUpdateProduct: 'Failed to update product',
    linkSale: 'Link Sale',
    enterSaleId: 'Enter Sale ID',
    saleLinkedSuccessfully: 'Sale linked successfully',
    failedToLinkSale: 'Failed to link sale',
    viewReports: 'View Reports',
    backupData: 'Backup Data',
    left: 'left',
    productsSold: 'products sold',

    // Products
    products: 'Products',
    category: 'Category',
    price: 'Price',
    stock: 'Stock',
    barcode: 'Barcode',
    addProduct: 'Add Product',
    saveProduct: 'Save Product',
    code: 'Code',
    description: 'Description',
    supplier: 'Supplier',
    markup: 'Markup',
    multiplier: 'Multiplier',
    profitUSD: 'Profit (USD)',
    nameRequired: 'Name is required.',
    pricePositive: 'Sale price must be a positive number.',

    // Sales
    sale: 'Sale',
    sales: 'Sales',
    totalAmount: 'Total Amount',
    discount: 'Discount',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    completeSale: 'Complete Sale',

    // Settings
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    appearance: 'Appearance',
    systemSettings: 'System Settings',
    theme: 'Theme',
    selectTheme: 'Choose your preferred color theme',
    darkMode: 'Dark Mode',
    darkModeDesc: 'Easy on the eyes',
    lightMode: 'Light Mode',
    lightModeDesc: 'Soft and comfortable',

    // Printing
    printReceipt: 'Print Receipt',
    printLabel: 'Print Label',
    printReport: 'Print Report',
    printer: 'Printer',

    // Auth
    login: 'Login',
    username: 'Username',
    password: 'Password',
    enterUsernameAndPassword: 'Please enter both username and password',
    invalidCredentials: 'Invalid username or password',
    loginFailed: 'Login failed',
    posSystem: 'Point of Sale System',
    enterUsername: 'Enter username',
    enterPassword: 'Enter password',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    copyright: '© 2024 EVA POS. All rights reserved.',

    // Backup
    createBackup: 'Create Backup',
    restoreBackup: 'Restore Backup',
    selectBackupFile: 'Select Backup File',

    // POS Page
    scanBarcode: 'Scan barcode...',
    scanReceiptBarcode: 'Scan the barcode from the receipt to automatically load sale information',
    returnToStock: 'Return to stock',
    exchangeReturningItem: 'Exchange - returning item',
    exchangeNewItem: 'Exchange - new item',
    scan: 'Scan',
    cart: 'Cart',
    item: 'item',
    items: 'items',
    clear: 'Clear',
    clearCart: 'Clear cart',
    clearAllItems: 'Clear all items from cart?',
    // returns: 'Returns', // Duplicate
    processReturns: 'Process returns',
    posTabs: 'POS Tabs',
    holdUpToCustomers: 'Hold up to {count} customers',
    emptyTab: 'Empty tab',
    empty: 'Empty',
    noItemsInCart: 'No items in cart.',
    itemHeader: 'Item',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    lineTotal: 'Line Total',
    removeItem: 'Remove item',
    customer: 'Customer',
    walkIn: 'Walk-in',
    // discount: 'Discount', // Duplicate
    discountByAmount: 'Discount by fixed amount',
    discountByPercent: 'Discount by percentage',
    discountByFinalPrice: 'Enter final price customer will pay',
    finalPrice: 'Final Price',
    enterFinalPrice: 'Enter final price',
    amount: 'Amount',
    percent: 'Percent',
    clearDiscount: 'Clear discount',
    // paymentMethod: 'Payment Method', // Duplicate
    // card: 'Card', // Duplicate
    mixed: 'Mixed',
    subtotal: 'Subtotal',
    total: 'Total',
    estimatedProfit: 'Estimated Profit',
    // completeSale: 'Complete Sale', // Duplicate
    processing: 'Processing…',
    addItemsFirst: 'Add items to cart first',
    completeSaleEnter: 'Complete sale (Enter)',
    outOfStock: 'is out of stock. Cannot add to cart.',
    onlyXAvailable: 'Only {count} {item} available in stock for "{name}".',
    outOfStockCannotAdd: 'is out of stock. Cannot add more.',
    addAtLeastOne: 'Add at least one product to the cart.',
    cannotCompleteOutOfStock: 'Cannot complete sale: The following items are out of stock: {items}. Please remove them from the cart.',
    cannotCompleteQuantity: 'Cannot complete sale: Quantity exceeds available stock for: {details}. Please adjust quantities.',
    failedToCompleteSale: 'Failed to complete sale.',
    pleaseEnterBarcode: 'Please enter a barcode or SKU (at least 5 characters)',
    inCart: 'in cart',
    added: 'Added',
    noMatchFor: 'No match for',
    loadMoreProducts: 'Load More Products',
    productsLoadedTitle: '{count} products loaded. Click to load more.',
    loadMoreCount: 'Load More Products ({count} loaded)',
    loaded: 'loaded',
    tab: 'Tab',
    saleCompleted: 'Sale completed successfully!',

    // Settings
    configureSystem: 'Configure your system settings',
    selectLanguage: 'Select your preferred language',
    englishLanguage: 'English',
    arabicLanguage: 'Arabic',
    exchangeRate: 'Exchange Rate (USD → IQD)',
    setExchangeRate: 'Set the current exchange rate for currency conversion',
    currentRate: 'Current Rate',
    per1USD: 'per 1 USD',
    updateExchangeRate: 'Update Exchange Rate',
    enterNewRate: 'Enter new rate',
    update: 'Update',
    updating: 'Updating...',
    exchangeRateUpdated: 'Exchange rate updated successfully!',
    profitMarginCalculator: 'Profit Margin Calculator',
    calculateProfitMargins: 'Calculate profit margins based on cost and selling price',
    costUSD: 'Cost (USD)',
    salePriceIQD: 'Sale Price (IQD)',
    profitMargin: 'Profit Margin',
    profitAmount: 'Profit Amount',
    exchangeRateUsed: 'Exchange Rate Used',
    formula: 'Formula',
    marginFormula: 'Margin = ((Sale Price - Cost × Rate) / (Cost × Rate)) × 100',
    moreSettingsComing: 'More settings coming soon...',
    labelSettings: 'Label Settings',
    customizeBarcodeLabels: 'Customize how barcode labels are printed',
    basicSettings: 'Basic Settings',
    labelSize: 'Label Size',
    smallLabel: '2" × 1" (Small)',
    largeLabel: '4" × 2" (Large)',
    fontSize: 'Font Size (px)',
    textAlignment: 'Text Alignment',
    leftAlignment: 'Left',
    center: 'Center',
    right: 'Right',
    labelPadding: 'Label Padding (px)',
    showHideElements: 'Show/Hide Elements',
    // productName: 'Product Name', // Duplicate
    variantColorSize: 'Variant (Color/Size)',
    sku: 'SKU',
    // price: 'Price', // Duplicate
    barcodeSettings: 'Barcode Settings',
    barcodeHeight: 'Barcode Height',
    barcodeWidth: 'Barcode Width',
    customTextFields: 'Custom Text Fields',
    addCustomText: 'Add custom text that appears on all labels (e.g., "VIP", "BIG SIZE", etc.)',
    customText1: 'Custom Text 1',
    customText2: 'Custom Text 2',
    customText2Auto: 'Automatically set to product name',
    customText3: 'Custom Text 3',
    storeName: 'Store Name',
    saveLabelSettings: 'Save Label Settings',
    labelSettingsSaved: 'Label settings saved successfully!',
    receiptSettings: 'Receipt Settings',
    customizeReceipts: 'Customize how your sales receipts look',
    storeNameOnReceipt: 'Store Name on Receipt',
    footerText: 'Footer Text (Terms & Conditions)',
    showLogo: 'Show Logo',
    showBarcode: 'Show Barcode',
    showCashier: 'Show Cashier Name',
    showCustomer: 'Show Customer Name',
    uploadLogo: 'Upload Logo',
    logoPreview: 'Logo Preview',
    receiptSettingsSaved: 'Receipt settings saved successfully!',

    // Barcode Label Modal
    printBarcodeLabel: 'Print Barcode Label',
    quantity: 'Quantity',
    // printer: 'Printer', // Duplicate
    systemDefault: 'System Default',
    preview: 'Preview',
    size: 'Size',
    customizeInSettings: 'Customize label settings in Settings page',
    loadingLabelSettings: 'Loading label settings...',
    thisProductNoBarcode: 'This product does not have a barcode assigned. Please add a barcode first.',
    barcodeNotReady: 'Barcode is not ready. Please wait a moment and try again.',

    // Common errors and messages
    pleaseEnterValidRate: 'Please enter a valid rate',
    failedToUpdateRate: 'Failed to update rate',
    desktopBridgeUnavailable: 'Desktop bridge is unavailable.',
    generatingPDF: 'Generating PDF - save dialog will appear',
    pdfGenerated: 'PDF generated successfully',
    failedToPrintLabel: 'Failed to print label {index}: {error}',
    failedToGenerateLabel: 'Failed to generate label: {error}',
    failedToLoadData: 'Failed to load data.',
    exampleVIP: 'e.g., VIP',
    exampleStoreName: 'e.g., EVA CLOTHING',

    // Products Page
    manageCatalog: 'Manage catalog, pricing, and variants.',
    importExcel: 'Import Excel',
    // addProduct: 'Add Product', // Duplicate
    loadingProducts: 'Loading products…',
    adjustStock: 'Adjust Stock',
    actions: 'ACTIONS',
    // stock: 'STOCK', // Duplicate
    avgCostUSD: 'AVG COST (USD)',
    priceIQD: 'PRICE (IQD)',
    // size: 'SIZE', // Duplicate
    color: 'COLOR',
    // barcode: 'BARCODE', // Duplicate
    // sku: 'SKU', // Duplicate
    name: 'NAME',
    areYouSureDelete: 'Are you sure you want to delete "{name}" ({sku})? This action cannot be undone.',
    failedToLoadProducts: 'Failed to load products.',
    failedToCreateProduct: 'Failed to create product.',
    failedToDeleteVariant: 'Failed to delete product variant.',
    failedToAdjustStock: 'Failed to adjust stock.',

    // Suppliers Page
    newSupplier: 'New Supplier',
    createSupplier: 'Create Supplier',
    supplierName: 'Name',
    contactName: 'Contact Name',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    notes: 'Notes',
    saveSupplier: 'Save Supplier',
    // saving: 'Saving…', // Duplicate
    loadingSuppliers: 'Loading suppliers…',
    noSuppliersYet: 'No suppliers yet. Add your first vendor.',
    supplierNameRequired: 'Supplier name is required.',
    failedToCreateSupplier: 'Failed to create supplier.',
    failedToLoadSuppliers: 'Failed to load suppliers.',
    active: 'Active',
    inactive: 'Inactive',

    // Purchase Orders Page
    purchaseOrders: 'Purchase Orders',
    trackInboundStock: 'Track inbound stock and supplier invoices.',
    createPO: 'Create PO',
    addItems: 'Add Items',
    selectSupplier: 'Select supplier',
    reference: 'Reference',
    draftItems: 'Draft Items',
    noItemsInDraft: 'No items in the draft. Add variants to build a PO',
    subtotalUSD: 'Subtotal USD',
    subtotalIQD: 'Subtotal IQD',
    recentPurchaseOrders: 'Recent Purchase Orders',
    loadingPurchaseOrders: 'Loading purchase orders…',
    noPurchaseOrdersRecorded: 'No purchase orders recorded.',
    selectSupplierAndAddItems: 'Select a supplier and add at least one item.',
    failedToLoadPurchaseOrders: 'Failed to load purchase orders.',
    failedToCreatePO: 'Failed to create PO.',

    // Customers Page
    customersLoyalty: 'Customers & Loyalty',
    trackLoyalty: 'Track loyalty, visits, and purchase history.',
    newCustomer: 'New Customer',
    searchCustomers: 'Search customers...',
    addCustomer: 'Add Customer',
    saveCustomer: 'Save Customer',
    loadingCustomers: 'Loading customers…',
    noCustomersMatch: 'No customers match your search.',
    noPhone: 'No phone',
    visits: 'Visits',
    spent: 'Spent',
    totalSpent: 'Total Spent',
    selectCustomerToView: 'Select a customer to view details.',
    noPhoneOnFile: 'No phone on file',
    noRecordedPurchases: 'No recorded purchases.',
    customerNameRequired: 'Customer name is required.',
    failedToLoadCustomers: 'Failed to load customers.',

    failedToCreateCustomer: 'Failed to create customer.',
    failedToLoadHistory: 'Failed to load history.',
    platinum: 'Platinum',
    gold: 'Gold',
    silver: 'Silver',
    bronze: 'Bronze',
    new: 'New',
    loyaltyPoints: 'Loyalty Points',
    purchaseHistory: 'Purchase History',
    unknownMethod: 'Unknown method',
    any: 'Any',

    // Returns Page
    returnsExchanges: 'Returns & Exchanges',
    processRefunds: 'Process refunds, returns, and exchanges quickly.',
    completeReturn: 'Complete Return',
    addItem: 'Add Item',
    refundTotal: 'Refund Total',
    type: 'Type',
    saleIDOptional: 'Sale ID (optional)',
    enterSaleID: 'Enter sale ID',
    lookup: 'lookup',
    reason: 'Reason',
    reasonOrNotes: 'Reason or notes',
    returnItems: 'Return Items',
    noItemsAddedYet: 'No items added yet.',
    recentReturns: 'Recent Returns',
    loadingReturns: 'Loading returns…',
    noReturnsRecorded: 'No returns recorded.',
    // processing: 'Processing…', // Duplicate
    failedToLoadReports: 'Failed to load reports.',
    failedToPrintReport: 'Failed to print report',
    unknownError: 'Unknown error',
    analysis: 'Analysis',
    revenueIQD: 'Revenue (IQD)',
    costOfGoods: 'Cost of Goods',
    inventoryValue: 'Current Stock Value',
    totalValueInclSold: 'Stock Value (Incl. Sold)',
    soldQuantity: 'Sold Qty',
    soldValueUSD: 'Sold Value (USD)',
    totalValueAllTime: 'Total Value (All Time)',
    totalStockCount: 'Total Items in Stock',
    createVoucher: 'Create Voucher',
    searchCustomer: 'Search Customer (Name or Phone)',
    searchByNameOrPhone: 'Type name or phone...',
    noCustomersFound: 'No customers found',
    selected: 'Selected',
    printVoucher: 'Print Voucher',
    discountPercent: 'Discount %',
    validityDays: 'Validity (Days)',
    peakHours: 'Peak Hours',
    peakDays: 'Peak Days',
    hourOfDay: 'Hour of Day (0-23)',
    dayOfWeek: 'Day of Week',
    peakHour: 'Peak Hour',
    peakDay: 'Peak Day',
    // total is already defined above
    leastProfitableItems: 'Least Profitable Items',
    leastProfitableSuppliers: 'Least Profitable Suppliers',
    inventoryAging: 'Inventory Aging',
    marginPercent: 'Margin %',
    daysInStock: 'Days in Stock',
    lastSold: 'Last Sold',
    neverSold: 'Never Sold',
    startDate: 'Start Date',
    runReportToSeeData: 'Run the report to see data.',
    dailySalesSummary: 'Daily Sales Summary',
    noSalesInRange: 'No sales in this range.',
    ordersReport: 'Orders',
    bestSellingItems: 'Best Selling Items',
    salesIQD: 'Sales (IQD)',
    salesBySize: 'Sales by Size',
    salesReport: 'Sales',
    salesByColor: 'Sales by Color',
    colorReport: 'Color',
    topCustomers: 'Top Customers',
    spend: 'Spend',
    lowStockAlerts: 'Low Stock Alerts',
    stockLevelsHealthy: 'Stock levels look healthy.',
    skuReport: 'SKU',
    expensesVsSales: 'Expenses vs Sales',
    expensesReport: 'Expenses',
    activityLogs: 'Activity Logs',
    time: 'Time',
    user: 'User',
    action: 'Action',
    invalidBarcodeFormat: 'Invalid barcode format. Expected format: SALE[number] or [number]',
    failedToFindSale: 'Failed to find sale.',
    invalidBarcodeScanReceipt: 'Invalid barcode. Please scan a receipt barcode (format: SALE[number]).',
    addAtLeastOneItemReturn: 'Add at least one item to process a return.',
    apiUnavailable: 'API unavailable or not authenticated.',
    missingVariantInfo: 'Some items are missing variant information. Please remove and re-add them.',
    itemMissingVariantId: 'Item "{name}" is missing variant ID',
    failedToProcessReturn: 'Failed to process return.',
    orScanReceiptBarcode: 'or scan receipt barcode',
    reasonReturn: 'Reason',
    id: 'ID',
    date: 'Date',
    selectVariant: 'Select Variant',
    addToReturn: 'Add to Return',
    anyVariant: 'Any',
    failedToCompleteReturn: 'Failed to complete return.',
    returnWithReceipt: 'Return with receipt',
    returnWithoutReceipt: 'Return without receipt',
    exchange: 'Exchange',

    // Expenses Page
    // expenses: 'Expenses', // Duplicate
    trackOperatingCosts: 'Track operating costs and profitability.',
    exportToCSV: 'Export to CSV',
    // total: 'Total', // Duplicate
    startDateExpense: 'Start Date',
    endDate: 'End Date',
    // category: 'Category', // Duplicate
    all: 'All',
    addExpense: 'Add Expense',
    amountIQD: 'Amount (IQD)',
    dateExpense: 'Date',
    saveExpense: 'Save Expense',
    selectOrTypeCategory: 'Select or type a category',
    loadingExpenses: 'Loading expenses…',
    noExpensesInRange: 'No expenses in this range.',
    failedToLoadExpenses: 'Failed to load expenses.',
    failedToSaveExpense: 'Failed to save expense.',
    failedToDeleteExpense: 'Failed to delete expense.',



    // Reports Page
    advancedReports: 'Advanced Reports',
    endToEndInsight: 'End-to-end insight into your clothing store performance.',
    // print: 'Print', // Duplicate
    exportToExcel: 'Export to Excel',
    runReport: 'Run Report',
    // loading: 'Loading…', // Duplicate
    // revenueIQD: 'Revenue (IQD)', // Duplicate
    // costOfGoods: 'Cost of Goods', // Duplicate
    // netProfit: 'Net Profit', // Duplicate
    // inventoryValue: 'Inventory Value', // Duplicate
    inventoryBySupplier: 'Inventory by Supplier',
    valueUSD: 'Value (USD)',
    noSupplierAssigned: 'No Supplier',
    selectedTotal: 'Selected Total',
    clearSelection: 'Clear Selection',
    viewDetails: 'View Details',
    noProductsFound: 'No products found. Add your first item.',
    uncategorized: 'Uncategorized',
    noBarcode: 'No barcode',
    manageVendorRelationships: 'Manage vendor relationships and contact details.',
    status: 'Status',

    // Sales History
    backToSalesList: 'Back to Sales List',
    saleInformation: 'Sale Information',
    saleId: 'Sale ID',
    returned: 'Returned',
    confirmDeleteSale: 'Are you sure you want to delete Sale #{id}? This will revert stock and customer stats.',
    noSalesFound: 'No sales found for the selected date range',

    // Backup
    backupAndRestore: 'Backup & Restore',
    manageBackups: 'Manage database backups and restore from previous versions.',
    createBackupNow: 'Create Backup Now',
    backupDirectory: 'Backup Directory',
    dailyBackupNote: 'Note: Daily automatic backups run every 24 hours. Manual backups can be created at any time. Only admins can restore backups.',
    noBackupsFound: 'No backups found. Create your first backup above.',
    filename: 'Filename',
    created: 'Created',
    restoring: 'Restoring...',
    deleting: 'Deleting...',
    restore: 'Restore',
    restoringDatabase: 'Restoring Database...',
    pleaseWaitRestart: 'Please wait. The application will restart automatically when finished.',
    accessDeniedBackup: 'Access denied. Only admin or manager can manage backups.',
    backupCreatedSuccess: 'Backup created successfully: {filename}',
    confirmRestore: 'Are you sure you want to restore from "{filename}"?\n\nThis will replace your current database. The app will restart after restoration.',
    backupRestoredSuccess: 'Backup restored successfully. The app will restart...',
    confirmDeleteBackup: 'Are you sure you want to delete "{filename}"?',
    backupDeletedSuccess: 'Backup deleted successfully.',
    failedToCreateBackup: 'Failed to create backup.',
    failedToRestoreBackup: 'Failed to restore backup.',
    failedToDeleteBackup: 'Failed to delete backup.',

    // Settings Page
    databaseMaintenance: 'Database & Maintenance',
    databaseReset: 'Database Reset',
    resetDatabaseButton: '⚠️ Reset Database (Delete All Data)',
    resetDatabaseHint: 'This will delete all sales, products, and customers. It cannot be undone.',
    softwareUpdate: 'Software Update',
    checkForUpdates: 'Check for Updates',
    checkingUpdates: 'Checking GitHub for releases...',
    updateAvailable: '✅ Update Available! Version {version}',
    downloadingAuto: 'Downloading automatically...',
    latestVersion: '✅ You are on the latest version.',
    downloadingUpdate: '⬇️ Downloading update... {percent}%',
    updateReady: '🚀 Update Ready! Restart the app to install.',
    restartNow: '🔄 Restart Now',
    updateError: '❌ Error: {error}',
    devModeUpdate: 'Updates are disabled in Development Mode. Build the app to test updates.',
  },

  ar: {
    // App
    appName: 'إيفا نقاط البيع',

    // Navigation
    dashboard: 'لوحة التحكم',
    pointOfSale: 'نقطة البيع',
    inventory: 'المخزون',
    purchasing: 'المشتريات',
    customers: 'العملاء',
    returns: 'المرتجعات',
    expenses: 'المصروفات',
    reports: 'التقارير',
    settings: 'الإعدادات',
    users: 'المستخدمين',
    branches: 'الفروع',
    backup: 'النسخ الاحتياطي',
    logout: 'تسجيل الخروج',
    suppliers: 'الموردين',
    offlineMode: 'غير متصل',
    lockPOS: 'قفل نقطة البيع',
    unlockPOS: 'فتح نقطة البيع',
    locked: 'مقفلة',
    unlocked: 'مفتوحة',

    // Date Presets
    today: 'اليوم',
    yesterday: 'أمس',
    last2days: 'آخر يومين',
    last7days: 'آخر 7 أيام',
    last30days: 'آخر 30 يوم',
    last90days: 'آخر 90 يوم',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    customRange: 'فترة مخصصة',
    to: 'إلى',

    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    print: 'طباعة',
    close: 'إغلاق',
    refresh: 'تحديث',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    error: 'خطأ',
    success: 'نجح',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',

    // Dashboard
    welcomeBack: 'مرحباً بعودتك',
    todaySales: 'مبيعات اليوم',
    totalRevenue: 'إجمالي الإيرادات',
    totalProfit: 'إجمالي الربح',
    lowStock: 'منتجات منخفضة المخزون',
    avgTicket: 'متوسط الفاتورة',
    netProfit: 'صافي الربح',
    transactions: 'معاملات',
    perSale: 'لكل عملية بيع',
    margin: 'هامش',
    afterExpenses: 'بعد المصروفات',
    needAttention: 'تحتاج انتباه',
    allGood: 'كل شيء جيد',
    todaysTotal: 'إجمالي اليوم',
    recentSales: 'المبيعات الأخيرة',
    lowStockAlert: 'تنبيه المخزون المنخفض',
    viewAll: 'عرض الكل',
    noSalesToday: 'لا توجد مبيعات اليوم',
    startSelling: 'ابدأ البيع',
    allItemsInStock: 'جميع المنتجات متوفرة',
    quickActions: 'إجراءات سريعة',
    newSale: 'عملية بيع جديدة',
    viewReports: 'عرض التقارير',
    backupData: 'نسخ احتياطي للبيانات',
    left: 'متبقي',
    productsSold: 'منتج مباع',

    // Products
    products: 'المنتجات',
    productName: 'اسم المنتج',
    category: 'الفئة',
    price: 'السعر',
    stock: 'المخزون',
    barcode: 'الباركود',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل منتج',
    saveProduct: 'حفظ المنتج',
    code: 'الرمز',
    description: 'الوصف',
    supplier: 'المورد',
    markup: 'هامش الربح',
    multiplier: 'المضاعف',
    profitUSD: 'الربح (USD)',
    nameRequired: 'الاسم مطلوب.',
    pricePositive: 'يجب أن يكون سعر البيع رقماً موجباً.',
    sellingPriceIQD: 'سعر البيع (IQD)',
    saving: 'جاري الحفظ...',
    failedToUpdateProduct: 'فشل في تحديث المنتج',
    linkSale: 'ربط بيعة',
    enterSaleId: 'أدخل رقم البيعة',
    saleLinkedSuccessfully: 'تم ربط البيعة بنجاح',
    failedToLinkSale: 'فشل في ربط البيعة',

    // Sales
    sale: 'بيع',
    sales: 'المبيعات',
    totalAmount: 'المبلغ الإجمالي',
    discount: 'الخصم',
    paymentMethod: 'طريقة الدفع',
    cash: 'نقدي',
    card: 'بطاقة',
    completeSale: 'إتمام البيع',

    // Settings
    language: 'اللغة',
    english: 'الإنجليزية',
    arabic: 'العربية',
    appearance: 'المظهر',
    systemSettings: 'إعدادات النظام',
    theme: 'المظهر',
    selectTheme: 'اختر مظهر الألوان المفضل لديك',
    darkMode: 'الوضع الداكن',
    darkModeDesc: 'مريح للعين',
    lightMode: 'الوضع الفاتح',
    lightModeDesc: 'ناعم ومريح',

    // Printing
    printReceipt: 'طباعة إيصال',
    printLabel: 'طباعة ملصق',
    printReport: 'طباعة تقرير',
    printer: 'الطابعة',

    // Auth
    login: 'تسجيل الدخول',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    enterUsernameAndPassword: 'يرجى إدخال اسم المستخدم وكلمة المرور',
    invalidCredentials: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    loginFailed: 'فشل تسجيل الدخول',
    posSystem: 'نظام نقاط البيع',
    enterUsername: 'أدخل اسم المستخدم',
    enterPassword: 'أدخل كلمة المرور',
    signingIn: 'جاري تسجيل الدخول...',
    signIn: 'تسجيل الدخول',
    copyright: '© 2024 EVA POS. جميع الحقوق محفوظة.',

    // Backup
    createBackup: 'إنشاء نسخة احتياطية',
    restoreBackup: 'استعادة نسخة احتياطية',
    selectBackupFile: 'اختيار ملف النسخة',

    // POS Page
    scanBarcode: 'امسح الباركود...',
    scanReceiptBarcode: 'امسح الباركود من الإيصال لتحميل معلومات البيع تلقائياً',
    returnToStock: 'إرجاع إلى المخزون',
    exchangeReturningItem: 'تبديل - إرجاع عنصر',
    exchangeNewItem: 'تبديل - عنصر جديد',
    scan: 'امسح',
    cart: 'السلة',
    item: 'عنصر',
    items: 'عناصر',
    clear: 'مسح',
    clearCart: 'مسح السلة',
    clearAllItems: 'مسح جميع العناصر من السلة؟',
    // returns: 'المرتجعات', // Duplicate
    processReturns: 'معالجة المرتجعات',
    posTabs: 'تبويبات نقطة البيع',
    holdUpToCustomers: 'يمكن الاحتفاظ بما يصل إلى {count} عملاء',
    emptyTab: 'تبويب فارغ',
    empty: 'فارغ',
    noItemsInCart: 'لا توجد عناصر في السلة.',
    itemHeader: 'العنصر',
    qty: 'الكمية',
    unitPrice: 'سعر الوحدة',
    lineTotal: 'الإجمالي',
    removeItem: 'إزالة العنصر',
    customer: 'العميل',
    walkIn: 'مشاة',
    // discount: 'الخصم', // Duplicate
    discountByAmount: 'خصم بمبلغ ثابت',
    discountByPercent: 'خصم بنسبة مئوية',
    discountByFinalPrice: 'أدخل السعر النهائي الذي سيدفعه العميل',
    finalPrice: 'السعر النهائي',
    enterFinalPrice: 'أدخل السعر النهائي',
    amount: 'المبلغ',
    percent: 'النسبة',
    clearDiscount: 'مسح الخصم',
    // paymentMethod: 'طريقة الدفع', // Duplicate
    // card: 'بطاقة', // Duplicate
    mixed: 'مختلط',
    subtotal: 'المجموع الفرعي',
    total: 'الإجمالي',
    estimatedProfit: 'الربح المقدر',
    // completeSale: 'إتمام البيع', // Duplicate
    processing: 'جاري المعالجة…',
    addItemsFirst: 'أضف عناصر إلى السلة أولاً',
    completeSaleEnter: 'إتمام البيع (Enter)',
    outOfStock: 'نفد من المخزون. لا يمكن إضافته إلى السلة.',
    onlyXAvailable: 'متوفر فقط {count} {item} في المخزون لـ "{name}".',
    outOfStockCannotAdd: 'نفد من المخزون. لا يمكن إضافة المزيد.',
    addAtLeastOne: 'أضف منتجاً واحداً على الأقل إلى السلة.',
    cannotCompleteOutOfStock: 'لا يمكن إتمام البيع: العناصر التالية نفدت من المخزون: {items}. يرجى إزالتها من السلة.',
    cannotCompleteQuantity: 'لا يمكن إتمام البيع: الكمية تتجاوز المخزون المتاح لـ: {details}. يرجى تعديل الكميات.',
    failedToCompleteSale: 'فشل إتمام البيع.',
    pleaseEnterBarcode: 'يرجى إدخال باركود أو رمز SKU (5 أحرف على الأقل)',
    inCart: 'في السلة',
    added: 'تمت إضافة',
    noMatchFor: 'لا يوجد تطابق لـ',
    loadMoreProducts: 'تحميل المزيد من المنتجات',
    productsLoadedTitle: 'تم تحميل {count} منتج. انقر لتحميل المزيد.',
    loadMoreCount: 'تحميل المزيد من المنتجات ({count} تم تحميلها)',
    loaded: 'تم تحميلها',
    tab: 'تبويب',
    saleCompleted: 'تمت عملية البيع بنجاح!',

    // Settings
    configureSystem: 'تكوين إعدادات النظام',
    selectLanguage: 'اختر لغتك المفضلة',
    englishLanguage: 'الإنجليزية',
    arabicLanguage: 'العربية',
    exchangeRate: 'سعر الصرف (USD → IQD)',
    setExchangeRate: 'تعيين سعر الصرف الحالي لتحويل العملة',
    currentRate: 'السعر الحالي',
    per1USD: 'لكل 1 دولار',
    updateExchangeRate: 'تحديث سعر الصرف',
    enterNewRate: 'أدخل سعر جديد',
    update: 'تحديث',
    updating: 'جاري التحديث...',
    exchangeRateUpdated: 'تم تحديث سعر الصرف بنجاح!',
    profitMarginCalculator: 'حاسبة هامش الربح',
    calculateProfitMargins: 'احسب هوامش الربح بناءً على التكلفة وسعر البيع',
    costUSD: 'التكلفة (USD)',
    salePriceIQD: 'سعر البيع (IQD)',
    profitMargin: 'هامش الربح',
    profitAmount: 'مبلغ الربح',
    exchangeRateUsed: 'سعر الصرف المستخدم',
    formula: 'الصيغة',
    marginFormula: 'الهامش = ((سعر البيع - التكلفة × السعر) / (التكلفة × السعر)) × 100',
    moreSettingsComing: 'المزيد من الإعدادات قريباً...',
    labelSettings: 'إعدادات الملصقات',
    customizeBarcodeLabels: 'تخصيص كيفية طباعة ملصقات الباركود',
    basicSettings: 'الإعدادات الأساسية',
    labelSize: 'حجم الملصق',
    smallLabel: '2" × 1" (صغير)',
    largeLabel: '4" × 2" (كبير)',
    fontSize: 'حجم الخط (بكسل)',
    textAlignment: 'محاذاة النص',
    leftAlignment: 'يسار',
    center: 'وسط',
    right: 'يمين',
    labelPadding: 'الحشو (بكسل)',
    showHideElements: 'إظهار/إخفاء العناصر',
    // productName: 'اسم المنتج', // Duplicate
    variantColorSize: 'المتغير (اللون/المقاس)',
    sku: 'رمز SKU',
    // price: 'السعر', // Duplicate
    barcodeSettings: 'إعدادات الباركود',
    barcodeHeight: 'ارتفاع الباركود',
    barcodeWidth: 'عرض الباركود',
    customTextFields: 'حقول النص المخصصة',
    addCustomText: 'أضف نصاً مخصصاً يظهر على جميع الملصقات (مثل "VIP"، "BIG SIZE"، إلخ)',
    customText1: 'النص المخصص 1',
    customText2: 'النص المخصص 2',
    customText2Auto: 'يتم تعيينه تلقائياً إلى اسم المنتج',
    customText3: 'النص المخصص 3',
    storeName: 'اسم المتجر',
    saveLabelSettings: 'حفظ إعدادات الملصقات',
    labelSettingsSaved: 'تم حفظ إعدادات الملصقات بنجاح!',
    receiptSettings: 'إعدادات الإيصال',
    customizeReceipts: 'تخصيص شكل إيصالات المبيعات الخاصة بك',
    storeNameOnReceipt: 'اسم المتجر على الإيصال',
    footerText: 'نص التذييل (الشروط والأحكام)',
    showLogo: 'إظهار الشعار',
    showBarcode: 'إظهار الباركود',
    showCashier: 'إظهار اسم الكاشير',
    showCustomer: 'إظهار اسم العميل',
    uploadLogo: 'رفع الشعار',
    logoPreview: 'معاينة الشعار',
    receiptSettingsSaved: 'تم حفظ إعدادات الإيصال بنجاح!',

    // Barcode Label Modal
    printBarcodeLabel: 'طباعة ملصق الباركود',
    quantity: 'الكمية',
    // printer: 'الطابعة', // Duplicate
    systemDefault: 'الافتراضي للنظام',
    preview: 'معاينة',
    size: 'الحجم',
    customizeInSettings: 'تخصيص إعدادات الملصقات في صفحة الإعدادات',
    loadingLabelSettings: 'جاري تحميل إعدادات الملصقات...',
    thisProductNoBarcode: 'هذا المنتج لا يحتوي على باركود. يرجى إضافة باركود أولاً.',
    barcodeNotReady: 'الباركود غير جاهز. يرجى الانتظار قليلاً والمحاولة مرة أخرى.',

    // Common errors and messages
    pleaseEnterValidRate: 'يرجى إدخال سعر صحيح',
    failedToUpdateRate: 'فشل تحديث السعر',
    desktopBridgeUnavailable: 'جسر سطح المكتب غير متاح.',
    generatingPDF: 'جاري إنشاء ملف PDF - سيظهر مربع حوار الحفظ',
    pdfGenerated: 'تم إنشاء ملف PDF بنجاح',
    failedToPrintLabel: 'فشل طباعة الملصق {index}: {error}',
    failedToGenerateLabel: 'فشل إنشاء الملصق: {error}',
    failedToLoadData: 'فشل تحميل البيانات.',
    exampleVIP: 'مثال: VIP',
    exampleStoreName: 'مثال: إيفا للملابس',

    // Products Page
    manageCatalog: 'إدارة الكتالوج والأسعار والمتغيرات.',
    importExcel: 'استيراد Excel',
    // addProduct: 'إضافة منتج', // Duplicate
    loadingProducts: 'جاري تحميل المنتجات…',
    adjustStock: 'تعديل المخزون',
    actions: 'الإجراءات',
    // stock: 'المخزون', // Duplicate
    avgCostUSD: 'متوسط التكلفة (USD)',
    priceIQD: 'السعر (IQD)',
    // size: 'المقاس', // Duplicate
    color: 'اللون',
    // barcode: 'الباركود', // Duplicate
    // sku: 'رمز SKU', // Duplicate
    name: 'الاسم',
    areYouSureDelete: 'هل أنت متأكد أنك تريد حذف "{name}" ({sku})؟ لا يمكن التراجع عن هذا الإجراء.',
    failedToLoadProducts: 'فشل تحميل المنتجات.',
    failedToCreateProduct: 'فشل إنشاء المنتج.',
    failedToDeleteVariant: 'فشل حذف متغير المنتج.',
    failedToAdjustStock: 'فشل تعديل المخزون.',

    // Suppliers Page
    newSupplier: 'مورد جديد',

    // Sales History
    backToSalesList: 'العودة إلى قائمة المبيعات',
    saleInformation: 'معلومات البيع',
    saleId: 'رقم البيع',
    returned: 'مرتجع',
    confirmDeleteSale: 'هل أنت متأكد أنك تريد حذف عملية البيع رقم {id}؟ سيؤدي هذا إلى التراجع عن إحصائيات المخزون والعملاء.',
    noSalesFound: 'لم يتم العثور على مبيعات في الفترة المحددة',

    // Backup
    backupAndRestore: 'النسخ الاحتياطي والاستعادة',
    manageBackups: 'إدارة نسخ قاعدة البيانات الاحتياطية والاستعادة من الإصدارات السابقة.',
    createBackupNow: 'إنشاء نسخة احتياطية الآن',
    backupDirectory: 'دليل النسخ الاحتياطي',
    dailyBackupNote: 'ملاحظة: يتم تشغيل النسخ الاحتياطي التلقائي يوميًا كل 24 ساعة. يمكن إنشاء نسخ احتياطية يدوية في أي وقت. يمكن للمسؤولين فقط استعادة النسخ الاحتياطية.',
    noBackupsFound: 'لم يتم العثور على نسخ احتياطية. قم بإنشاء أول نسخة احتياطية أعلاه.',
    filename: 'اسم الملف',
    created: 'تاريخ الإنشاء',
    restoring: 'جاري الاستعادة...',
    deleting: 'جاري الحذف...',
    restore: 'استعادة',
    restoringDatabase: 'جاري استعادة قاعدة البيانات...',
    pleaseWaitRestart: 'يرجى الانتظار. سيتم إعادة تشغيل التطبيق تلقائيًا عند الانتهاء.',
    accessDeniedBackup: 'تم رفض الوصول. يمكن للمسؤول أو المدير فقط إدارة النسخ الاحتياطية.',
    backupCreatedSuccess: 'تم إنشاء النسخة الاحتياطية بنجاح: {filename}',
    confirmRestore: 'هل أنت متأكد أنك تريد الاستعادة من "{filename}"؟\n\nسيؤدي هذا إلى استبدال قاعدة البيانات الحالية. سيتم إعادة تشغيل التطبيق بعد الاستعادة.',
    backupRestoredSuccess: 'تم استعادة النسخة الاحتياطية بنجاح. سيتم إعادة تشغيل التطبيق...',
    confirmDeleteBackup: 'هل أنت متأكد أنك تريد حذف "{filename}"؟',
    backupDeletedSuccess: 'تم حذف النسخة الاحتياطية بنجاح.',
    failedToCreateBackup: 'فشل إنشاء النسخة الاحتياطية.',
    failedToRestoreBackup: 'فشل استعادة النسخة الاحتياطية.',
    failedToDeleteBackup: 'فشل حذف النسخة الاحتياطية.',
    createSupplier: 'إنشاء مورد',
    supplierName: 'الاسم',
    contactName: 'اسم جهة الاتصال',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    notes: 'ملاحظات',
    saveSupplier: 'حفظ المورد',
    // saving: 'جاري الحفظ…', // Duplicate
    loadingSuppliers: 'جاري تحميل الموردين…',
    noSuppliersYet: 'لا يوجد موردون بعد. أضف أول مورد.',
    supplierNameRequired: 'اسم المورد مطلوب.',
    failedToCreateSupplier: 'فشل إنشاء المورد.',
    failedToLoadSuppliers: 'فشل تحميل الموردين.',
    active: 'نشط',
    inactive: 'غير نشط',

    // Purchase Orders Page
    purchaseOrders: 'أوامر الشراء',
    trackInboundStock: 'تتبع المخزون الوارد وفواتير الموردين.',
    createPO: 'إنشاء أمر شراء',
    addItems: 'إضافة عناصر',
    selectSupplier: 'اختر مورد',
    reference: 'المرجع',
    draftItems: 'العناصر المسودة',
    noItemsInDraft: 'لا توجد عناصر في المسودة. أضف متغيرات لإنشاء أمر شراء',
    subtotalUSD: 'المجموع الفرعي USD',
    subtotalIQD: 'المجموع الفرعي IQD',
    recentPurchaseOrders: 'أوامر الشراء الأخيرة',
    loadingPurchaseOrders: 'جاري تحميل أوامر الشراء…',
    noPurchaseOrdersRecorded: 'لا توجد أوامر شراء مسجلة.',
    selectSupplierAndAddItems: 'اختر مورداً وأضف عنصراً واحداً على الأقل.',
    failedToLoadPurchaseOrders: 'فشل تحميل أوامر الشراء.',
    failedToCreatePO: 'فشل إنشاء أمر الشراء.',

    // Customers Page
    customersLoyalty: 'العملاء والولاء',
    trackLoyalty: 'تتبع الولاء والزيارات وسجل المشتريات.',
    newCustomer: 'عميل جديد',
    searchCustomers: 'بحث عن العملاء...',
    addCustomer: 'إضافة عميل',
    saveCustomer: 'حفظ العميل',
    loadingCustomers: 'جاري تحميل العملاء…',
    noCustomersMatch: 'لا يوجد عملاء يطابقون بحثك.',
    noPhone: 'لا يوجد هاتف',
    visits: 'الزيارات',
    spent: 'المصروف',
    totalSpent: 'إجمالي المصروف',
    selectCustomerToView: 'اختر عميلاً لعرض التفاصيل.',
    noPhoneOnFile: 'لا يوجد هاتف في الملف',
    noRecordedPurchases: 'لا توجد مشتريات مسجلة.',
    customerNameRequired: 'اسم العميل مطلوب.',
    failedToLoadCustomers: 'فشل تحميل العملاء.',

    failedToCreateCustomer: 'فشل إنشاء العميل.',
    failedToLoadHistory: 'فشل تحميل السجل.',
    platinum: 'بلاتيني',
    gold: 'ذهبي',
    silver: 'فضي',
    bronze: 'برونزي',
    new: 'جديد',
    loyaltyPoints: 'نقاط الولاء',
    purchaseHistory: 'سجل المشتريات',
    unknownMethod: 'طريقة غير معروفة',
    any: 'أي',

    // Returns Page
    returnsExchanges: 'المرتجعات والتبديلات',
    processRefunds: 'معالجة الاسترداد والمرتجعات والتبديلات بسرعة.',
    completeReturn: 'إتمام الإرجاع',
    addItem: 'إضافة عنصر',
    refundTotal: 'إجمالي الاسترداد',
    type: 'النوع',
    saleIDOptional: 'رقم البيع (اختياري)',
    enterSaleID: 'أدخل رقم البيع',
    lookup: 'بحث',
    reason: 'السبب',
    reasonOrNotes: 'السبب أو الملاحظات',
    returnItems: 'عناصر الإرجاع',
    noItemsAddedYet: 'لم تتم إضافة عناصر بعد.',
    recentReturns: 'المرتجعات الأخيرة',
    loadingReturns: 'جاري تحميل المرتجعات…',
    noReturnsRecorded: 'لا توجد مرتجعات مسجلة.',
    // processing: 'جاري المعالجة…', // Duplicate
    failedToLoadReports: 'فشل تحميل التقارير.',
    failedToPrintReport: 'فشل طباعة التقرير',
    unknownError: 'خطأ غير معروف',
    startDateExpense: 'تاريخ البدء',
    // todaySales: 'مبيعات اليوم', // Duplicate
    analysis: 'تحليل',
    revenueIQD: 'الإيرادات (د.ع)',
    costOfGoods: 'تكلفة البضائع',
    // netProfit: 'صافي الربح', // Duplicate
    inventoryValue: 'قيمة المخزون الحالي',
    totalValueInclSold: 'قيمة المخزون (شامل المباع - تكلفة)',
    soldQuantity: 'الكمية المباعة',
    soldValueUSD: 'قيمة المباع (USD)',
    totalValueAllTime: 'إجمالي القيمة (كل الوقت)',
    totalStockCount: 'العدد الكلي للمخزون',
    createVoucher: 'إنشاء قسيمة',
    searchCustomer: 'بحث العميل (الاسم أو الهاتف)',
    searchByNameOrPhone: 'اكتب الاسم أو رقم الهاتف...',
    noCustomersFound: 'لا يوجد عملاء',
    selected: 'تم الاختيار',
    printVoucher: 'طباعة القسيمة',
    discountPercent: 'نسبة الخصم',
    validityDays: 'صلاحية (أيام)',
    peakHours: 'ساعات الذروة',
    peakDays: 'أيام الذروة',
    hourOfDay: 'ساعة اليوم (0-23)',
    dayOfWeek: 'يوم الأسبوع',
    peakHour: 'ساعة الذروة',
    peakDay: 'يوم الذروة',
    // total is already defined above
    leastProfitableItems: 'أقل العناصر ربحية',
    leastProfitableSuppliers: 'أقل الموردين ربحية',
    inventoryAging: 'تقادم المخزون',
    marginPercent: 'نسبة الهامش',
    daysInStock: 'أيام في المخزون',
    lastSold: 'آخر بيع',
    neverSold: 'لم يُباع',
    // expenses: 'المصروفات', // Duplicate
    startDate: 'تاريخ البدء',
    runReportToSeeData: 'قم بتشغيل التقرير لرؤية البيانات.',
    dailySalesSummary: 'ملخص المبيعات اليومية',
    noSalesInRange: 'لا توجد مبيعات في هذا النطاق.',
    ordersReport: 'الطلبات',
    bestSellingItems: 'العناصر الأكثر مبيعاً',
    salesIQD: 'المبيعات (IQD)',
    salesBySize: 'المبيعات حسب الحجم',
    salesReport: 'المبيعات',
    salesByColor: 'المبيعات حسب اللون',
    colorReport: 'اللون',

    topCustomers: 'أفضل العملاء',
    spend: 'الإنفاق',
    lowStockAlerts: 'تنبيهات المخزون المنخفض',
    stockLevelsHealthy: 'مستويات المخزون تبدو جيدة.',
    skuReport: 'SKU',
    expensesVsSales: 'المصاريف مقابل المبيعات',
    expensesReport: 'المصاريف',
    activityLogs: 'سجلات النشاط',
    time: 'الوقت',
    user: 'المستخدم',
    action: 'الإجراء',
    invalidBarcodeFormat: 'تنسيق الباركود غير صالح. التنسيق المتوقع: SALE[number] أو [number]',
    failedToFindSale: 'فشل العثور على البيع.',
    invalidBarcodeScanReceipt: 'باركود غير صالح. يرجى مسح باركود الإيصال (التنسيق: SALE[number]).',
    addAtLeastOneItemReturn: 'أضف عنصراً واحداً على الأقل لمعالجة الإرجاع.',
    apiUnavailable: 'API غير متاح أو غير مصادق عليه.',
    missingVariantInfo: 'بعض العناصر تفتقد معلومات المتغير. يرجى إزالتها وإعادة إضافتها.',
    itemMissingVariantId: 'العنصر "{name}" يفتقد معرف المتغير',
    failedToProcessReturn: 'فشل معالجة الإرجاع.',
    orScanReceiptBarcode: 'أو امسح باركود الإيصال',

    reasonReturn: 'السبب',
    id: 'المعرف',
    date: 'التاريخ',
    selectVariant: 'اختر متغير',
    addToReturn: 'إضافة إلى الإرجاع',

    anyVariant: 'أي',
    failedToCompleteReturn: 'فشل إتمام الإرجاع.',
    returnWithReceipt: 'إرجاع مع إيصال',
    returnWithoutReceipt: 'إرجاع بدون إيصال',
    exchange: 'تبديل',

    // Expenses Page
    // expenses: 'المصروفات', // Duplicate
    trackOperatingCosts: 'تتبع تكاليف التشغيل والربحية.',
    exportToCSV: 'تصدير إلى CSV',
    // total: 'الإجمالي', // Duplicate
    // startDate: 'تاريخ البداية', // Duplicate
    endDate: 'تاريخ النهاية',
    // category: 'الفئة', // Duplicate
    all: 'الكل',
    addExpense: 'إضافة مصروف',
    amountIQD: 'المبلغ (IQD)',
    dateExpense: 'التاريخ',
    saveExpense: 'حفظ المصروف',
    selectOrTypeCategory: 'اختر أو اكتب فئة',
    loadingExpenses: 'جاري تحميل المصروفات…',
    noExpensesInRange: 'لا توجد مصروفات في هذا النطاق.',
    failedToLoadExpenses: 'فشل تحميل المصاريف.',
    failedToSaveExpense: 'فشل حفظ المصروف.',

    failedToDeleteExpense: 'فشل حذف المصروف.',


    // Reports Page
    advancedReports: 'التقارير المتقدمة',
    endToEndInsight: 'رؤية شاملة لأداء متجر الملابس الخاص بك.',
    // print: 'طباعة', // Duplicate
    exportToExcel: 'تصدير إلى Excel',
    runReport: 'تشغيل التقرير',
    // loading: 'جاري التحميل…', // Duplicate
    // revenueIQD: 'الإيرادات (IQD)', // Duplicate
    // costOfGoods: 'تكلفة البضائع', // Duplicate
    // netProfit: 'صافي الربح', // Duplicate
    // inventoryValue: 'قيمة المخزون', // Duplicate
    inventoryBySupplier: 'قيمة المخزون حسب المورد',
    valueUSD: 'القيمة (USD)',
    noSupplierAssigned: 'بدون مورد',
    selectedTotal: 'إجمالي المحدد',
    clearSelection: 'مسح التحديد',
    viewDetails: 'عرض التفاصيل',
    noProductsFound: 'لم يتم العثور على منتجات. أضف أول عنصر.',
    uncategorized: 'غير مصنف',
    noBarcode: 'لا يوجد باركود',
    manageVendorRelationships: 'إدارة علاقات الموردين وتفاصيل الاتصال.',
    status: 'الحالة',

    // Settings Page
    databaseMaintenance: 'قاعدة البيانات والصيانة',
    databaseReset: 'إعادة تعيين قاعدة البيانات',
    resetDatabaseButton: '⚠️ إعادة تعيين قاعدة البيانات (حذف جميع البيانات)',
    resetDatabaseHint: 'سيؤدي هذا إلى حذف جميع المبيعات والمنتجات والعملاء. لا يمكن التراجع عن هذا الإجراء.',
    softwareUpdate: 'تحديث البرنامج',
    checkForUpdates: 'التحقق من وجود تحديثات',
    checkingUpdates: 'جاري التحقق من التحديثات...',
    updateAvailable: '✅ يتوفر تحديث! الإصدار {version}',
    downloadingAuto: 'جاري التنزيل تلقائياً...',
    latestVersion: '✅ أنت تستخدم أحدث إصدار.',
    downloadingUpdate: '⬇️ جاري تنزيل التحديث... {percent}%',
    updateReady: '🚀 التحديث جاهز! أعد تشغيل التطبيق للتثبيت.',
    restartNow: '🔄 إعادة التشغيل الآن',
    updateError: '❌ خطأ: {error}',
    devModeUpdate: 'التحديثات معطلة في وضع التطوير. قم ببناء التطبيق لاختبار التحديثات.',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('appLanguage') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguageState(savedLanguage);
      applyLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
    applyLanguage(lang);
  };

  const applyLanguage = (lang: Language) => {
    // Set HTML dir attribute for RTL
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations['en']] || key;
    if (params) {
      Object.keys(params).forEach((paramKey) => {
        translation = translation.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }
    return translation;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
